### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ulogan** [ulogan/DAT_SF_16#1]
Testting for HW1

**Comment by sttung** [comment]
Cool project idea - is there a particular sector you'd be looking at price movement within? (e.g., renewable energy, oil / gas, healthcare costs..)  Is there something in your background that motivated this particular question? @breucopter @ghego

**Comment by ulogan** [comment]
Thanks Stephanie,

I work for a hedge fund and I am currently trying to use machine learning in predicting the daily price movement of the equity futures.

Regards

-Logan

**Comment by ghego** [comment]
Congrats! you found out how to cite us!

Keep rocking!

(you can close the issue now)

**Comment by ulogan** [comment]
Ok, Thanks

-Logan
